name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  check_circular_deps:
    name: Check for Circular Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install packages
        run: yarn --immutable
      - name: Check for circular dependencies
        run: yarn check-circular-deps
  tests_with_coverage:
    name: Testing With Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install packages
        run: corepack enable && yarn --immutable
      - name: Build packages
        run: yarn build
      - name: Type Test
        run: yarn type-test
      - name: Test with coverage
        run: yarn coverage
      - name: run integration tests
        run: yarn int-test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
