name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    name: Testing With Coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [ 20 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
#      - name: Install packages
#        run: corepack enable && yarn set version 3.5.0 && yarn install --immutable
      - name: Install packages
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Check Circular Deps
        run: yarn check-circular-deps
      - name: Test with coverage
        run: yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
